from pathlib import Path

Import("env")

PROJECT_DIR = Path(env.subst("$PROJECT_DIR"))
ENV_PATH = PROJECT_DIR / ".env.local"
OUT_PATH = PROJECT_DIR / "include" / "generated_env_config.h"

KEYS = {
    "WIFI_SSID": "",
    "WIFI_PASS": "",
    "SERVER_HOST": "",
    "UPLOAD_PATH": "/api/casio-ai/upload-photo",
    "SOLVE_PATH": "/api/casio-ai/solve",
    "QUESTION_RESULT_PATH": "/api/casio-ai/question",
    "QUESTION_BLOCK_PATH": "/api/casio-ai/question-block",
    "DEVICE_ID": "",
    "DEVICE_API_KEY": "",
    "FIXED_PHOTO_URL": "",
}


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        print("[env] .env.local not found; generated config will use blanks/default paths")
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if (
            len(value) >= 2
            and ((value[0] == '"' and value[-1] == '"') or (value[0] == "'" and value[-1] == "'"))
        ):
            value = value[1:-1]
        values[key] = value
    return values


def c_string(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
    )


values = KEYS.copy()
values.update({key: value for key, value in parse_env_file(ENV_PATH).items() if key in KEYS})

OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
lines = [
    "#pragma once",
    "",
    "// Generated by scripts/load_env.py from .env.local.",
    "// Do not commit generated_env_config.h.",
]
for key, value in values.items():
    lines.append(f'#define CASIO_{key} "{c_string(value)}"')
lines.append("")

OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
print(f"[env] generated {OUT_PATH.relative_to(PROJECT_DIR)} from .env.local")
